In [1]:
from __future__ import print_function
import torch

In [2]:
x = torch.empty(5,3)
x

tensor([[0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000]])

In [3]:
torch.rand(5,3)

tensor([[0.9683, 0.2969, 0.5077],
        [0.9795, 0.7050, 0.4188],
        [0.2289, 0.4750, 0.8737],
        [0.4078, 0.1713, 0.1348],
        [0.0370, 0.7345, 0.7824]])

In [4]:
torch.zeros(5,3,dtype=torch.long)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [7]:
x = torch.tensor([5.5,3])

In [9]:
x = x.new_ones(5,3,dtype=torch.double)
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [10]:
x = torch.rand_like(x,dtype=torch.float)

In [14]:
x.size()

torch.Size([5, 3])

In [15]:
y = torch.rand(5, 3)
x+y

tensor([[0.8160, 0.2320, 0.6313],
        [1.1077, 1.2510, 1.5160],
        [1.8133, 0.6742, 1.1855],
        [0.7805, 1.5182, 0.6713],
        [0.8653, 0.8914, 1.2760]])

In [16]:
torch.add(x, y)

tensor([[0.8160, 0.2320, 0.6313],
        [1.1077, 1.2510, 1.5160],
        [1.8133, 0.6742, 1.1855],
        [0.7805, 1.5182, 0.6713],
        [0.8653, 0.8914, 1.2760]])

In [17]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
result

tensor([[0.8160, 0.2320, 0.6313],
        [1.1077, 1.2510, 1.5160],
        [1.8133, 0.6742, 1.1855],
        [0.7805, 1.5182, 0.6713],
        [0.8653, 0.8914, 1.2760]])

In [18]:
y.add_(x)

tensor([[0.8160, 0.2320, 0.6313],
        [1.1077, 1.2510, 1.5160],
        [1.8133, 0.6742, 1.1855],
        [0.7805, 1.5182, 0.6713],
        [0.8653, 0.8914, 1.2760]])

In [20]:
x[:,1]

tensor([0.1534, 0.4587, 0.5183, 0.7269, 0.5774])

In [21]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [22]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.5568])
0.5568419098854065


In [23]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [24]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [25]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [26]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
